namespace Anomaly.Utils
{
    public enum AKeyCode : int
    {
        None = 0,

        #region Keyboard
        Space = 1 + ADevice.KeyboardShift,
        Enter = 2 + ADevice.KeyboardShift,
        Tab = 3 + ADevice.KeyboardShift,
        Backquote = 4 + ADevice.KeyboardShift,
        Quote = 5 + ADevice.KeyboardShift,
        Semicolon = 6 + ADevice.KeyboardShift,
        Comma = 7 + ADevice.KeyboardShift,
        Period = 8 + ADevice.KeyboardShift,
        Slash = 9 + ADevice.KeyboardShift,
        Backslash = 10 + ADevice.KeyboardShift,
        LeftBracket = 11 + ADevice.KeyboardShift,
        RightBracket = 12 + ADevice.KeyboardShift,
        Minus = 13 + ADevice.KeyboardShift,
        Equals = 14 + ADevice.KeyboardShift,
        A = 15 + ADevice.KeyboardShift,
        B = 16 + ADevice.KeyboardShift,
        C = 17 + ADevice.KeyboardShift,
        D = 18 + ADevice.KeyboardShift,
        E = 19 + ADevice.KeyboardShift,
        F = 20 + ADevice.KeyboardShift,
        G = 21 + ADevice.KeyboardShift,
        H = 22 + ADevice.KeyboardShift,
        I = 23 + ADevice.KeyboardShift,
        J = 24 + ADevice.KeyboardShift,
        K = 25 + ADevice.KeyboardShift,
        L = 26 + ADevice.KeyboardShift,
        M = 27 + ADevice.KeyboardShift,
        N = 28 + ADevice.KeyboardShift,
        O = 29 + ADevice.KeyboardShift,
        P = 30 + ADevice.KeyboardShift,
        Q = 31 + ADevice.KeyboardShift,
        R = 32 + ADevice.KeyboardShift,
        S = 33 + ADevice.KeyboardShift,
        T = 34 + ADevice.KeyboardShift,
        U = 35 + ADevice.KeyboardShift,
        V = 36 + ADevice.KeyboardShift,
        W = 37 + ADevice.KeyboardShift,
        X = 38 + ADevice.KeyboardShift,
        Y = 39 + ADevice.KeyboardShift,
        Z = 40 + ADevice.KeyboardShift,
        Digit1 = 41 + ADevice.KeyboardShift,
        Digit2 = 42 + ADevice.KeyboardShift,
        Digit3 = 43 + ADevice.KeyboardShift,
        Digit4 = 44 + ADevice.KeyboardShift,
        Digit5 = 45 + ADevice.KeyboardShift,
        Digit6 = 46 + ADevice.KeyboardShift,
        Digit7 = 47 + ADevice.KeyboardShift,
        Digit8 = 48 + ADevice.KeyboardShift,
        Digit9 = 49 + ADevice.KeyboardShift,
        Digit0 = 50 + ADevice.KeyboardShift,
        LeftShift = 51 + ADevice.KeyboardShift,
        RightShift = 52 + ADevice.KeyboardShift,
        LeftAlt = 53 + ADevice.KeyboardShift,
        RightAlt = 54 + ADevice.KeyboardShift,
        AltGr = 54 + ADevice.KeyboardShift,
        LeftCtrl = 55 + ADevice.KeyboardShift,
        RightCtrl = 56 + ADevice.KeyboardShift,
        LeftMeta = 57 + ADevice.KeyboardShift,
        LeftWindows = 57 + ADevice.KeyboardShift,
        LeftApple = 57 + ADevice.KeyboardShift,
        LeftCommand = 57 + ADevice.KeyboardShift,
        RightMeta = 58 + ADevice.KeyboardShift,
        RightWindows = 58 + ADevice.KeyboardShift,
        RightApple = 58 + ADevice.KeyboardShift,
        RightCommand = 58 + ADevice.KeyboardShift,
        ContextMenu = 59 + ADevice.KeyboardShift,
        Escape = 60 + ADevice.KeyboardShift,
        LeftArrow = 61 + ADevice.KeyboardShift,
        RightArrow = 62 + ADevice.KeyboardShift,
        UpArrow = 63 + ADevice.KeyboardShift,
        DownArrow = 64 + ADevice.KeyboardShift,
        Backspace = 65 + ADevice.KeyboardShift,
        PageDown = 66 + ADevice.KeyboardShift,
        PageUp = 67 + ADevice.KeyboardShift,
        Home = 68 + ADevice.KeyboardShift,
        End = 69 + ADevice.KeyboardShift,
        Insert = 70 + ADevice.KeyboardShift,
        Delete = 71 + ADevice.KeyboardShift,
        CapsLock = 72 + ADevice.KeyboardShift,
        NumLock = 73 + ADevice.KeyboardShift,
        PrintScreen = 74 + ADevice.KeyboardShift,
        ScrollLock = 75 + ADevice.KeyboardShift,
        Pause = 76 + ADevice.KeyboardShift,
        NumpadEnter = 77 + ADevice.KeyboardShift,
        NumpadDivide = 78 + ADevice.KeyboardShift,
        NumpadMultiply = 79 + ADevice.KeyboardShift,
        NumpadPlus = 80 + ADevice.KeyboardShift,
        NumpadMinus = 81 + ADevice.KeyboardShift,
        NumpadPeriod = 82 + ADevice.KeyboardShift,
        NumpadEquals = 83 + ADevice.KeyboardShift,
        Numpad0 = 84 + ADevice.KeyboardShift,
        Numpad1 = 85 + ADevice.KeyboardShift,
        Numpad2 = 86 + ADevice.KeyboardShift,
        Numpad3 = 87 + ADevice.KeyboardShift,
        Numpad4 = 88 + ADevice.KeyboardShift,
        Numpad5 = 89 + ADevice.KeyboardShift,
        Numpad6 = 90 + ADevice.KeyboardShift,
        Numpad7 = 91 + ADevice.KeyboardShift,
        Numpad8 = 92 + ADevice.KeyboardShift,
        Numpad9 = 93 + ADevice.KeyboardShift,
        F1 = 94 + ADevice.KeyboardShift,
        F2 = 95 + ADevice.KeyboardShift,
        F3 = 96 + ADevice.KeyboardShift,
        F4 = 97 + ADevice.KeyboardShift,
        F5 = 98 + ADevice.KeyboardShift,
        F6 = 99 + ADevice.KeyboardShift,
        F7 = 100 + ADevice.KeyboardShift,
        F8 = 101 + ADevice.KeyboardShift,
        F9 = 102 + ADevice.KeyboardShift,
        F10 = 103 + ADevice.KeyboardShift,
        F11 = 104 + ADevice.KeyboardShift,
        F12 = 105 + ADevice.KeyboardShift,
        OEM1 = 106 + ADevice.KeyboardShift,
        OEM2 = 107 + ADevice.KeyboardShift,
        OEM3 = 108 + ADevice.KeyboardShift,
        OEM4 = 109 + ADevice.KeyboardShift,
        OEM5 = 110 + ADevice.KeyboardShift,
        IMESelected = 111 + ADevice.KeyboardShift,
        #endregion

        #region Mouse
        MouseLeft = 1 + ADevice.MouseShift,
        MouseRight = 2 + ADevice.MouseShift,
        MouseMiddle = 3 + ADevice.MouseShift
        #endregion
    }

    public enum AAxisCode : int
    {
        None = 0,

        #region Keyboard
        Horizontal = 1 + ADevice.KeyboardShift,
        Vertical = 2 + ADevice.KeyboardShift,
        #endregion

        #region Mouse
        MouseX = 1 + ADevice.MouseShift,
        MouseY = 2 + ADevice.MouseShift
        #endregion
    }
}
