namespace Anomaly.Utils
{
    public enum AKeyCode : int
    {
        None = 0,

        #region Keyboard
        Space = 1 + Device.KeyboardShift,
        Enter = 2 + Device.KeyboardShift,
        Tab = 3 + Device.KeyboardShift,
        Backquote = 4 + Device.KeyboardShift,
        Quote = 5 + Device.KeyboardShift,
        Semicolon = 6 + Device.KeyboardShift,
        Comma = 7 + Device.KeyboardShift,
        Period = 8 + Device.KeyboardShift,
        Slash = 9 + Device.KeyboardShift,
        Backslash = 10 + Device.KeyboardShift,
        LeftBracket = 11 + Device.KeyboardShift,
        RightBracket = 12 + Device.KeyboardShift,
        Minus = 13 + Device.KeyboardShift,
        Equals = 14 + Device.KeyboardShift,
        A = 15 + Device.KeyboardShift,
        B = 16 + Device.KeyboardShift,
        C = 17 + Device.KeyboardShift,
        D = 18 + Device.KeyboardShift,
        E = 19 + Device.KeyboardShift,
        F = 20 + Device.KeyboardShift,
        G = 21 + Device.KeyboardShift,
        H = 22 + Device.KeyboardShift,
        I = 23 + Device.KeyboardShift,
        J = 24 + Device.KeyboardShift,
        K = 25 + Device.KeyboardShift,
        L = 26 + Device.KeyboardShift,
        M = 27 + Device.KeyboardShift,
        N = 28 + Device.KeyboardShift,
        O = 29 + Device.KeyboardShift,
        P = 30 + Device.KeyboardShift,
        Q = 31 + Device.KeyboardShift,
        R = 32 + Device.KeyboardShift,
        S = 33 + Device.KeyboardShift,
        T = 34 + Device.KeyboardShift,
        U = 35 + Device.KeyboardShift,
        V = 36 + Device.KeyboardShift,
        W = 37 + Device.KeyboardShift,
        X = 38 + Device.KeyboardShift,
        Y = 39 + Device.KeyboardShift,
        Z = 40 + Device.KeyboardShift,
        Digit1 = 41 + Device.KeyboardShift,
        Digit2 = 42 + Device.KeyboardShift,
        Digit3 = 43 + Device.KeyboardShift,
        Digit4 = 44 + Device.KeyboardShift,
        Digit5 = 45 + Device.KeyboardShift,
        Digit6 = 46 + Device.KeyboardShift,
        Digit7 = 47 + Device.KeyboardShift,
        Digit8 = 48 + Device.KeyboardShift,
        Digit9 = 49 + Device.KeyboardShift,
        Digit0 = 50 + Device.KeyboardShift,
        LeftShift = 51 + Device.KeyboardShift,
        RightShift = 52 + Device.KeyboardShift,
        LeftAlt = 53 + Device.KeyboardShift,
        RightAlt = 54 + Device.KeyboardShift,
        AltGr = 54 + Device.KeyboardShift,
        LeftCtrl = 55 + Device.KeyboardShift,
        RightCtrl = 56 + Device.KeyboardShift,
        LeftMeta = 57 + Device.KeyboardShift,
        LeftWindows = 57 + Device.KeyboardShift,
        LeftApple = 57 + Device.KeyboardShift,
        LeftCommand = 57 + Device.KeyboardShift,
        RightMeta = 58 + Device.KeyboardShift,
        RightWindows = 58 + Device.KeyboardShift,
        RightApple = 58 + Device.KeyboardShift,
        RightCommand = 58 + Device.KeyboardShift,
        ContextMenu = 59 + Device.KeyboardShift,
        Escape = 60 + Device.KeyboardShift,
        LeftArrow = 61 + Device.KeyboardShift,
        RightArrow = 62 + Device.KeyboardShift,
        UpArrow = 63 + Device.KeyboardShift,
        DownArrow = 64 + Device.KeyboardShift,
        Backspace = 65 + Device.KeyboardShift,
        PageDown = 66 + Device.KeyboardShift,
        PageUp = 67 + Device.KeyboardShift,
        Home = 68 + Device.KeyboardShift,
        End = 69 + Device.KeyboardShift,
        Insert = 70 + Device.KeyboardShift,
        Delete = 71 + Device.KeyboardShift,
        CapsLock = 72 + Device.KeyboardShift,
        NumLock = 73 + Device.KeyboardShift,
        PrintScreen = 74 + Device.KeyboardShift,
        ScrollLock = 75 + Device.KeyboardShift,
        Pause = 76 + Device.KeyboardShift,
        NumpadEnter = 77 + Device.KeyboardShift,
        NumpadDivide = 78 + Device.KeyboardShift,
        NumpadMultiply = 79 + Device.KeyboardShift,
        NumpadPlus = 80 + Device.KeyboardShift,
        NumpadMinus = 81 + Device.KeyboardShift,
        NumpadPeriod = 82 + Device.KeyboardShift,
        NumpadEquals = 83 + Device.KeyboardShift,
        Numpad0 = 84 + Device.KeyboardShift,
        Numpad1 = 85 + Device.KeyboardShift,
        Numpad2 = 86 + Device.KeyboardShift,
        Numpad3 = 87 + Device.KeyboardShift,
        Numpad4 = 88 + Device.KeyboardShift,
        Numpad5 = 89 + Device.KeyboardShift,
        Numpad6 = 90 + Device.KeyboardShift,
        Numpad7 = 91 + Device.KeyboardShift,
        Numpad8 = 92 + Device.KeyboardShift,
        Numpad9 = 93 + Device.KeyboardShift,
        F1 = 94 + Device.KeyboardShift,
        F2 = 95 + Device.KeyboardShift,
        F3 = 96 + Device.KeyboardShift,
        F4 = 97 + Device.KeyboardShift,
        F5 = 98 + Device.KeyboardShift,
        F6 = 99 + Device.KeyboardShift,
        F7 = 100 + Device.KeyboardShift,
        F8 = 101 + Device.KeyboardShift,
        F9 = 102 + Device.KeyboardShift,
        F10 = 103 + Device.KeyboardShift,
        F11 = 104 + Device.KeyboardShift,
        F12 = 105 + Device.KeyboardShift,
        OEM1 = 106 + Device.KeyboardShift,
        OEM2 = 107 + Device.KeyboardShift,
        OEM3 = 108 + Device.KeyboardShift,
        OEM4 = 109 + Device.KeyboardShift,
        OEM5 = 110 + Device.KeyboardShift,
        IMESelected = 111 + Device.KeyboardShift,
        #endregion

        #region Mouse
        MouseLeft = 1 + Device.MouseShift,
        MouseRight = 2 + Device.MouseShift,
        MouseMiddle = 3 + Device.MouseShift
        #endregion
    }

    public enum AAxisCode : int
    {
        None = 0,

        #region Keyboard
        Horizontal = 1 + Device.KeyboardShift,
        Vertical = 2 + Device.KeyboardShift,
        #endregion

        #region Mouse
        MouseX = 1 + Device.MouseShift,
        MouseY = 2 + Device.MouseShift
        #endregion
    }
}
